[Materials]
	heatSources = ["minecraft:lava=1000", "minecraft:magma_block=800", "powah:blazing_crystal_block=2800"]
	heatBlocksAPI = true
	coolantFluids = ["minecraft:water=1"]
	coolantFluidsAPI = true
