[TagConfig]
	ITEM_PREFERENCE = ["minecraft", "alltheores", "thermal", "immersiveengineering", "create", "mekanism", "jaopca", "kubejs", "appliedenergistics2", "pneumaticcraft", "occultism", "tmechworks", "industrialforegoing", "botania", "quark", "pedestals"]
