[world_generation]
	[world_generation.copper]
		shouldGenerate = false
	[world_generation.tin]
		shouldGenerate = false
	[world_generation.uranium]
		shouldGenerate = false
	[world_generation.lead]
		shouldGenerate = false
	[world_generation.osmium]
		shouldGenerate = false
