centrifugeTierCreativeMutliplier = 10
centrifugeTierCreativeSize = false
centrifugeMultiplierBlacklist = ["resourcefulbees:starry_honeycomb", "resourcefulbees:starry_honeycomb_block", "resourcefulbees:chaotic_honeycomb", "resourcefulbees:chaotic_honeycomb_block"]
