[General]
	compactingRules = ["minecraft:clay, minecraft:clay_ball, 4", "powah:uraninite_raw_dense, powah:uraninite_raw, 2", "powah:uraninite_raw, powah:uraninite_raw_poor, 2", "compressium:sand_2, compressium:sand_1, 9", "compressium:sand_1, minecraft:sand, 9"]
	